import Link from "next/link";
import { redirect } from "next/navigation";
import { createSupabaseServerClient } from "@/lib/supabase/server";
import { addAutomation, toggleAutomation } from "../intelligence/actions";

export default async function AutomationsPage() {
  const supabase = await createSupabaseServerClient();
  const { data: userData } = await supabase.auth.getUser();
  if (!userData.user) redirect("/login");
  const { data: membership } = await supabase.from("workspace_members").select("workspace_id").eq("user_id", userData.user.id).limit(1).maybeSingle();
  if (!membership) redirect("/dashboard");
  const { data: rules } = await supabase.from("automation_rules").select("*").eq("workspace_id", membership.workspace_id).order("created_at", { ascending: false });
  return <main className="shell"><header className="topbar"><div><div className="eyebrow">Workflow engine</div><h1>Automations</h1><p className="muted">Define repeatable release operations now; connect live execution services as integrations are added.</p></div><nav className="nav-links"><Link className="button ghost" href="/command-center">Command</Link><Link className="button ghost" href="/studio">Studio</Link><Link className="button ghost" href="/analytics">Analytics</Link></nav></header>
  <section className="grid two-col"><div className="stack"><div className="card"><h2>Active rules</h2>{(rules ?? []).length ? (rules ?? []).map((rule)=><div className="row" key={rule.id}><div><div className="tag-row"><span className="pill">{rule.trigger_type}</span><span className="pill">{rule.action_type}</span></div><strong>{rule.name}</strong><p className="muted">When: {rule.trigger_config?.detail || rule.trigger_type}<br/>Then: {rule.action_config?.detail || rule.action_type}</p></div><form action={toggleAutomation}><input type="hidden" name="id" value={rule.id}/><input type="hidden" name="enabled" value={String(rule.enabled)}/><button className={`button ${rule.enabled ? "primary" : "ghost"}`} type="submit">{rule.enabled ? "Enabled" : "Disabled"}</button></form></div>) : <div className="empty">No automation rules yet.</div>}</div>
  <div className="card"><h2>Recommended recipes</h2><div className="row"><div><strong>Reply creates follow-up</strong><p className="muted">When a curator replies, create a response task and move the target to replied.</p></div><span className="pill">CRM</span></div><div className="row"><div><strong>Release-day checklist</strong><p className="muted">When release day arrives, surface distribution, social, email, and monitoring tasks.</p></div><span className="pill">Release</span></div><div className="row"><div><strong>Placement amplification</strong><p className="muted">When an outcome is accepted or placed, create a thank-you and share workflow.</p></div><span className="pill">Growth</span></div></div></div>
  <form action={addAutomation} className="card stack"><h2>Create rule</h2><label className="field"><span>Name</span><input className="input" name="name" required placeholder="Release-day launch checklist"/></label><label className="field"><span>Trigger</span><select className="input" name="triggerType"><option value="release_date">Release date</option><option value="reply_received">Reply received</option><option value="outcome_recorded">Outcome recorded</option><option value="follow_up_due">Follow-up due</option><option value="metric_threshold">Metric threshold</option><option value="content_published">Content published</option></select></label><label className="field"><span>Trigger detail</span><textarea className="input textarea" name="triggerDetail"/></label><label className="field"><span>Action</span><select className="input" name="actionType"><option value="create_task">Create task</option><option value="create_recommendation">Create recommendation</option><option value="update_relationship">Update relationship</option><option value="create_content_idea">Create content idea</option><option value="notify_owner">Notify owner</option></select></label><label className="field"><span>Action detail</span><textarea className="input textarea" name="actionDetail"/></label><button className="button primary" type="submit">Create automation</button></form></section></main>;
}
