import { publicVerifiedRoutes, type PublicVerifiedRoute } from "@/lib/public-verified-routes";

export const additionalVerifiedRadioRoutes: PublicVerifiedRoute[] = [
  {
    name: "CJTR 91.3 FM / AccessNow Radio",
    lane: "radio",
    type: "Community radio",
    status: "Open",
    route: "Official station submission guidance",
    requirements: "For local music, AccessNow says to email jo.bates@myaccess.coop with subject MUSIC SUBMISSION. For general digital distribution, the station recommends !earshot Distro as the preferred route.",
    checked: "August 18, 2026",
    source: "https://accessnowradio.ca/contact/",
  },
  {
    name: "KCPR 91.3 FM",
    lane: "radio",
    type: "College radio",
    status: "Open",
    route: "Music and Programming contact",
    requirements: "Use KCPR's current official Music and Programming contact on its Contact page. ArtistOS does not reconstruct the protected email from obfuscated HTML.",
    checked: "August 16, 2026",
    source: "https://kcpr.org/contact/",
  },
  {
    name: "KCSB 91.9 FM",
    lane: "radio",
    type: "College/community radio",
    status: "Open",
    route: "Artist Inquiry form / Music Director route",
    requirements: "Use KCSB's current Artist Inquiry form for artist opportunities or the current Music Director route and published mailing addresses for music intake.",
    checked: "August 16, 2026",
    source: "https://www.kcsb.org/artist-inquiry/",
  },
  {
    name: "KRUI 89.7 FM",
    lane: "radio",
    type: "College radio",
    status: "Open",
    route: "Music submission email",
    requirements: "KRUI's current music page directs airplay submissions to krui.music@gmail.com and asks artists to include artist information plus a track list with explicit-track notes.",
    checked: "August 16, 2026",
    source: "https://krui.fm/about/music/",
  },
  {
    name: "KWVA 88.1 FM",
    lane: "radio",
    type: "College radio",
    status: "Open",
    route: "Physical music submission + Music Director contact",
    requirements: "KWVA invites band demos and music donations by mail. music@kwvaradio.org is the current Music Director contact for discussing interviews and on-air opportunities.",
    checked: "August 18, 2026",
    source: "https://kwva.uoregon.edu/send-us-your-music",
  },
  {
    name: "WCBN 88.3 FM",
    lane: "radio",
    type: "College/community radio",
    status: "Open with physical-media workflow",
    route: "Hard-copy submission",
    requirements: "WCBN says it accepts music from musicians who send a hard copy. Address general submissions to WCBN MUSIC using the station's current mailing instructions.",
    checked: "August 16, 2026",
    source: "https://wcbn.org/c/",
  },
  {
    name: "WFUV 90.7 FM",
    lane: "radio",
    type: "Public/college radio",
    status: "Open with physical-mail workflow",
    route: "Mail to Music Department",
    requirements: "WFUV's current guidance says to send music by snail mail to the Music Department. musicdept@wfuv.org is listed for general music questions rather than as the stated submission method.",
    checked: "August 16, 2026",
    source: "https://wfuv.org/wfuv-contact-staff",
  },
  {
    name: "WMBR 88.1 FM",
    lane: "radio",
    type: "College radio",
    status: "Open",
    route: "Music Department contact workflow",
    requirements: "WMBR's current site directs music and band information to the Music Department. Its current email is image-obfuscated, so ArtistOS links to the official contact workflow instead of guessing a plaintext address.",
    checked: "August 16, 2026",
    source: "https://www.wmbr.org/?p=mail",
  },
  {
    name: "WNYU 89.1 FM",
    lane: "radio",
    type: "College radio",
    status: "Open",
    route: "Digital email or physical media",
    requirements: "WNYU accepts digital submissions to music@wnyu.org and physical CDs, CD-Rs, LPs, 12-inch, 10-inch, and 7-inch releases. Physical submissions are prioritized.",
    checked: "August 18, 2026",
    source: "https://wnyu.org/about",
  },
  {
    name: "WPRB 103.3 FM",
    lane: "radio",
    type: "College/community radio",
    status: "Open",
    route: "Music submission email or physical mail",
    requirements: "Use music@wprb.com for music submissions and inquiries. WPRB prioritizes physical submissions; program@wprb.com is for DJ/show proposals, not music submissions.",
    checked: "August 16, 2026",
    source: "https://wprb.com/music-submissions/",
  },
  {
    name: "WRUR 88.5 FM",
    lane: "radio",
    type: "Public/college radio",
    status: "Open",
    route: "Physical or uncompressed digital",
    requirements: "WRUR accepts CDs and uncompressed digital downloads, preferably by links or Dropbox rather than email attachments. music@wrur.org is the current information contact.",
    checked: "August 18, 2026",
    source: "https://www.wrur.org/contact",
  },
  {
    name: "WTBU Radio",
    lane: "radio",
    type: "College radio",
    status: "Open",
    route: "Music Director email",
    requirements: "WTBU says artists interested in sending an album should contact the Music Directors at music@wtburadio.org.",
    checked: "August 18, 2026",
    source: "https://www.wtburadio.org/contact-us/",
  },
  {
    name: "WXDU 88.7 FM",
    lane: "radio",
    type: "College/community radio",
    status: "Open",
    route: "Music airplay submission email",
    requirements: "WXDU explicitly accepts music for airplay at music@wxdu.org and says Bandcamp YUM codes are preferred over other download methods.",
    checked: "August 18, 2026",
    source: "https://www.wxdu.org/contact",
  },
  {
    name: "WXYC 89.3 FM",
    lane: "radio",
    type: "College/community radio",
    status: "Open",
    route: "Official music-submission contact page",
    requirements: "WXYC's current Contact page explicitly provides a dedicated email route for music submissions/distribution concerns plus a physical Music Department address. ArtistOS links to the official page rather than republishing an address the site currently obscures.",
    checked: "August 18, 2026",
    source: "https://wxyc.org/contact",
  },
];

export const expandedPublicVerifiedRoutes: PublicVerifiedRoute[] = [
  ...publicVerifiedRoutes,
  ...additionalVerifiedRadioRoutes,
];

export function expandedRoutesByLane(lane: PublicVerifiedRoute["lane"]) {
  return expandedPublicVerifiedRoutes.filter((route) => route.lane === lane);
}
