export type PublicVerifiedRoute = {
  name: string;
  lane: "radio" | "press" | "sync";
  type: string;
  status: string;
  route: string;
  requirements: string;
  checked: string;
  source: string;
};

export const publicVerifiedRoutes: PublicVerifiedRoute[] = [
  {
    name: "KEXP",
    lane: "radio",
    type: "Radio",
    status: "Open",
    route: "Digital submission email",
    requirements: "Send streaming/download links to md@kexp.org. Do not send attachments.",
    checked: "August 13, 2026",
    source: "https://www.kexp.org/about/submission-guidelines/",
  },
  {
    name: "KCSU 90.5 FM",
    lane: "radio",
    type: "College radio",
    status: "Open",
    route: "Official submission form",
    requirements: "Use the current digital submission form. music@kcsufm.com is listed for music-department contact.",
    checked: "August 13, 2026",
    source: "https://kcsufm.com/submitmusic/",
  },
  {
    name: "KJHK 90.7 FM",
    lane: "radio",
    type: "College radio",
    status: "Open",
    route: "Digital submission email",
    requirements: "Current electronic submission route: submitmusic@kjhk.org.",
    checked: "August 13, 2026",
    source: "https://kjhk.org/web/submit-music/",
  },
  {
    name: "KALX 90.7 FM",
    lane: "radio",
    type: "College radio",
    status: "Open with restrictions",
    route: "Physical mail",
    requirements: "Professionally pressed CDs or LPs only. Current instructions reject digital submissions and streaming/download links.",
    checked: "August 13, 2026",
    source: "https://www.kalx.berkeley.edu/about/contact/",
  },
  {
    name: "Radio K (KUOM)",
    lane: "radio",
    type: "College radio",
    status: "Open",
    route: "Physical or digital",
    requirements: "Accepts physical releases and digital submissions through the Music Department workflow; digital submissions should use downloadable files or supported download links.",
    checked: "August 13, 2026",
    source: "https://radiok.org/submitting-music",
  },
  {
    name: "CFRU 93.3 FM",
    lane: "radio",
    type: "Community radio",
    status: "Open with eligibility rules",
    route: "Digital music department",
    requirements: "General digital submissions should be an EP or album with at least three distinct songs. Download links are preferred; high-quality MP3s are recommended.",
    checked: "August 13, 2026",
    source: "https://www.cfru.ca/music/",
  },
  {
    name: "CFCR 90.5 FM",
    lane: "radio",
    type: "Community radio",
    status: "Open",
    route: "Music Director email",
    requirements: "CFCR's official contact page labels md@cfcr.ca for Music Submissions and Music Director / Promotions Director contact.",
    checked: "August 13, 2026",
    source: "https://cfcr.ca/contact/",
  },
  {
    name: "CHLY 101.7 FM",
    lane: "radio",
    type: "Community radio",
    status: "Open with restrictions",
    route: "Official music submission form",
    requirements: "Use CHLY's submission form; submissions@chly.ca is the fallback if the form cannot be used. CHLY currently states that it does not accept AI-generated music.",
    checked: "August 13, 2026",
    source: "https://www.chly.ca/submissions",
  },
  {
    name: "CHRW 94.9 FM / Radio Western",
    lane: "radio",
    type: "Campus-community radio",
    status: "Open",
    route: "Music submission email",
    requirements: "Radio Western's current official site directs new music submissions and promotion to music@radiowestern.ca.",
    checked: "August 13, 2026",
    source: "https://radiowestern.ca/",
  },
  {
    name: "KZSU 90.1 FM",
    lane: "radio",
    type: "College radio",
    status: "Open",
    route: "Digital email or physical mail",
    requirements: "Digital submissions can be sent to music@kzsu.stanford.edu; the station also publishes a physical mailing route.",
    checked: "August 13, 2026",
    source: "https://kzsu.stanford.edu/contact/",
  },
  {
    name: "WREK 91.1 FM",
    lane: "radio",
    type: "College radio",
    status: "Open",
    route: "Music Director email or mail",
    requirements: "Current WREK music information supports contacting music.director@wrek.org and a physical submission workflow.",
    checked: "August 13, 2026",
    source: "https://www.wrek.org/music",
  },
  {
    name: "WVFS 89.7 FM",
    lane: "radio",
    type: "College radio",
    status: "Open",
    route: "Digital or physical",
    requirements: "WVFS accepts CD, vinyl, and digital submissions. Its digital guidance asks artists to use links rather than attachments.",
    checked: "August 13, 2026",
    source: "https://wvfs.fsu.edu/contact/how-to-submit-music/",
  },
  {
    name: "Radio Milwaukee",
    lane: "radio",
    type: "Public radio",
    status: "Open",
    route: "Official music submission form",
    requirements: "Send uncompressed audio (WAV preferred), mixed/mastered material, radio edits, and an information document. No physical media. The general artist route is separate from the station's DJ-mix form.",
    checked: "August 16, 2026",
    source: "https://radiomilwaukee.org/music-submission",
  },
  {
    name: "WESU 88.1 FM",
    lane: "radio",
    type: "College/community radio",
    status: "Open",
    route: "Music Director email",
    requirements: "Contact wesumd@wesufm.org and SEND LINKS (Dropbox, Google Drive, Spotify, Apple Music, or similar). WESU explicitly asks submitters not to send files that consume station storage.",
    checked: "August 16, 2026",
    source: "https://www.wesufm.org/contact-us/",
  },
  {
    name: "CFUV 101.9 FM",
    lane: "radio",
    type: "Campus/community radio",
    status: "Open with eligibility rules",
    route: "Digital submission email",
    requirements: "Send at least three unique tracks by digital download link to music@cfuv.ca; MP3 minimum 320 kbps. Physical submissions are generally limited to local Victoria-area artists.",
    checked: "August 16, 2026",
    source: "https://cfuv.uvic.ca/music-submissions/",
  },
  {
    name: "CKCU 93.1 FM",
    lane: "radio",
    type: "Campus/community radio",
    status: "Open through show-specific outreach",
    route: "Contact relevant show hosts directly",
    requirements: "CKCU's current guidance says artists should review the program grid, identify shows that play similar music, and contact those hosts directly using their program-page contact information.",
    checked: "August 16, 2026",
    source: "https://www.ckcufm.com/contact/",
  },
  {
    name: "KXSC Radio",
    lane: "radio",
    type: "College radio",
    status: "Open",
    route: "Email or physical mail",
    requirements: "Email submissions to submissions@kxsc.org or send a physical package. KXSC asks submitters to allow two or three weeks before following up.",
    checked: "August 16, 2026",
    source: "https://kxsc.org/musicsubmission/",
  },
  {
    name: "KSCU 103.3 FM",
    lane: "radio",
    type: "College radio",
    status: "Open",
    route: "Music Director email",
    requirements: "KSCU's official About page says to submit music for airplay to music@kscu.org.",
    checked: "August 16, 2026",
    source: "https://kscu.org/about/",
  },
  {
    name: "KDVS 90.3 FM",
    lane: "radio",
    type: "College/community radio",
    status: "Open with physical-only restriction",
    route: "Physical mail",
    requirements: "KDVS currently says all new music submissions are physical-only and should be mailed to the Music Department. musicdept@kdvs.org is the current Music Director contact, not a digital-submission route.",
    checked: "August 16, 2026",
    source: "https://kdvs.org/about/faq",
  },
  {
    name: "Electric Hawk",
    lane: "press",
    type: "Electronic music press",
    status: "Open",
    route: "Official feature form",
    requirements: "Current Get Featured workflow accepts music for editorial consideration, social support, and playlist consideration through the official form.",
    checked: "August 13, 2026",
    source: "https://theelectrichawk.com/get-featured-on-electric-hawk/",
  },
  {
    name: "Magnetic Magazine",
    lane: "press",
    type: "Music publication / label",
    status: "Open",
    route: "Separate editorial and demo routes",
    requirements: "Editorial music goes to the publication's current music-review inbox; label demos use the separate Magnetic Magazine Recordings demo inbox.",
    checked: "August 13, 2026",
    source: "https://magneticmag.com/contact/",
  },
  {
    name: "EDM Identity",
    lane: "press",
    type: "Electronic music press",
    status: "Open",
    route: "Dedicated track-submission contact",
    requirements: "EDM Identity's official Contact page provides a dedicated track-submission route and asks submitters to send links rather than attachments.",
    checked: "August 13, 2026",
    source: "https://edmidentity.com/contact/",
  },
  {
    name: "Atwood Magazine",
    lane: "press",
    type: "Independent music publication",
    status: "Open",
    route: "Editorial email",
    requirements: "Pitch mitch@atwoodmagazine.com with one direct music link and 2-3 sentences of context. One follow-up maximum; exclusive premieres require at least 21 days notice.",
    checked: "August 16, 2026",
    source: "https://atwoodmagazine.com/pitching-us/",
  },
  {
    name: "ThinkSync Music",
    lane: "sync",
    type: "Sync / music supervision",
    status: "Open with eligibility rules",
    route: "Dedicated submissions inbox",
    requirements: "Commercially released artists can submit a small set of MP3s by download link to the supervision submissions route; placement/publishing submissions use a separate inbox.",
    checked: "August 13, 2026",
    source: "https://thinksyncmusic.com/contact/submissions/",
  },
];

export function routesByLane(lane: PublicVerifiedRoute["lane"]) {
  return publicVerifiedRoutes.filter((route) => route.lane === lane);
}
