export type SourceCoverage = {
  slug: string;
  label: string;
  connection: "live_api" | "oauth_api" | "catalog_api" | "paid_api" | "export" | "public";
  status: "available" | "configuration_required" | "export_required" | "paid_key_required" | "limited";
  summary: string;
  metrics: string[];
  limitation?: string;
};

export const SOURCE_COVERAGE: SourceCoverage[] = [
  {
    slug: "youtube",
    label: "YouTube / YouTube Music",
    connection: "oauth_api",
    status: "configuration_required",
    summary: "Channel totals and owned-channel analytics through Google OAuth.",
    metrics: ["subscribers", "channel views", "videos", "28-day views", "watch minutes", "subscriber gains/losses"],
    limitation: "The YouTube Data API and YouTube Analytics API must be enabled in the connected Google Cloud project.",
  },
  {
    slug: "soundcharts",
    label: "Soundcharts pilot",
    connection: "live_api",
    status: "configuration_required",
    summary: "Cross-platform audience, Spotify monthly listeners, playlist entries, charts, radio, and social observations through a licensed API.",
    metrics: ["monthly listeners", "followers", "playlist entries", "charts", "radio", "social audience"],
    limitation: "Soundcharts offers a free sandbox and 1,000 initial production requests. Endpoint access still depends on the account plan and credentials.",
  },
  {
    slug: "kit",
    label: "Kit email audience",
    connection: "live_api",
    status: "configuration_required",
    summary: "Aggregate subscriber and broadcast performance from the owned Kit account.",
    metrics: ["active subscribers", "broadcast recipients", "opens", "clicks", "unsubscribes", "open rate", "click rate"],
    limitation: "Requires a Kit v4 API key. ArtistOS stores aggregate metrics only in the first slice, not raw subscriber records.",
  },
  {
    slug: "spotify",
    label: "Spotify",
    connection: "catalog_api",
    status: "limited",
    summary: "Catalog identity, releases, tracks, and URLs through the Web API; private artist analytics through export or a licensed provider.",
    metrics: ["catalog metadata", "release identity", "track identity", "Spotify for Artists export"],
    limitation: "Spotify removed artist follower and popularity fields from the Web API in February 2026. Streams and monthly listeners are not available from the public API.",
  },
  {
    slug: "apple-music",
    label: "Apple Music",
    connection: "catalog_api",
    status: "configuration_required",
    summary: "Public catalog, charts, playlists, artist and release identity through Apple Music API; private artist analytics through Apple Music for Artists exports.",
    metrics: ["catalog metadata", "charts", "playlists", "plays export", "listeners export", "Shazam counts"],
    limitation: "The catalog API requires an Apple developer token. Apple Music for Artists analytics are still export-derived.",
  },
  {
    slug: "instagram",
    label: "Instagram / Facebook",
    connection: "oauth_api",
    status: "configuration_required",
    summary: "Professional-account reach, engagement, audience, and content performance through Meta OAuth.",
    metrics: ["followers", "reach", "impressions", "engagement", "reel/video performance"],
    limitation: "Requires a professional Instagram account connected to a Facebook Page and a configured Meta app.",
  },
  {
    slug: "tiktok",
    label: "TikTok",
    connection: "oauth_api",
    status: "configuration_required",
    summary: "Account and video metrics where TikTok grants approved API access; exports remain supported.",
    metrics: ["followers", "profile views", "video views", "likes", "shares", "comments"],
  },
  {
    slug: "lastfm",
    label: "Last.fm",
    connection: "live_api",
    status: "configuration_required",
    summary: "Free-key public popularity, track playcount, similar-artist, and chart signals.",
    metrics: ["listeners", "playcount", "track playcount", "similar artists", "charts"],
    limitation: "Requires a free Last.fm API key and is a public discovery signal, not a DSP royalty or artist-dashboard source.",
  },
  {
    slug: "listenbrainz",
    label: "ListenBrainz",
    connection: "public",
    status: "available",
    summary: "Open listens-derived popularity, statistics, recommendations, and similar-artist signals.",
    metrics: ["popularity", "listen counts", "similar artists", "recommendations"],
    limitation: "Coverage reflects listens submitted to ListenBrainz and should be treated as a directional open-data signal.",
  },
  {
    slug: "musicbrainz",
    label: "MusicBrainz",
    connection: "public",
    status: "limited",
    summary: "Canonical artist, release, recording, ISRC, barcode, label, and relationship metadata.",
    metrics: ["artist identity", "release identity", "recordings", "ISRC", "barcode", "relationships"],
    limitation: "The public web service is free for non-commercial use, limited to one request per second, and requires commercial terms review for a commercial ArtistOS product.",
  },
  {
    slug: "ticketmaster",
    label: "Ticketmaster Discovery",
    connection: "live_api",
    status: "configuration_required",
    summary: "Free-key event, venue, attraction, geography, and ticket-link intelligence.",
    metrics: ["events", "venues", "markets", "dates", "ticket links"],
    limitation: "Coverage varies by market and requires a Ticketmaster developer key.",
  },
  {
    slug: "distrokid",
    label: "DistroKid / distributor reports",
    connection: "export",
    status: "export_required",
    summary: "Royalty and store-level performance from distributor CSV exports.",
    metrics: ["streams", "earnings", "store", "territory", "release", "reporting period"],
    limitation: "DistroKid does not provide a general public analytics API for this use case.",
  },
  {
    slug: "chartmetric",
    label: "Chartmetric",
    connection: "paid_api",
    status: "paid_key_required",
    summary: "Licensed cross-platform artist, playlist, chart, audience, and competitor intelligence.",
    metrics: ["playlist movement", "charts", "audience", "social growth", "competitor benchmarks"],
    limitation: "Evaluate only after the Soundcharts pilot identifies concrete coverage gaps.",
  },
  {
    slug: "viberate",
    label: "Viberate",
    connection: "paid_api",
    status: "paid_key_required",
    summary: "Licensed artist analytics, audience, playlist, festival, and industry benchmarks.",
    metrics: ["artist performance", "audience", "playlists", "industry benchmarks"],
    limitation: "API pricing currently starts at EUR 300 per month, so this adapter is deferred while lower-cost coverage is tested.",
  },
  {
    slug: "soundcloud",
    label: "SoundCloud",
    connection: "oauth_api",
    status: "configuration_required",
    summary: "Profile, track, play, like, repost, and comment data where API access is approved.",
    metrics: ["followers", "plays", "likes", "reposts", "comments"],
  },
  {
    slug: "bandcamp",
    label: "Bandcamp",
    connection: "export",
    status: "export_required",
    summary: "Direct-to-fan sales, supporters, and geography through exports and public release metadata.",
    metrics: ["sales", "supporters", "revenue", "territory"],
  },
];

export const SOURCE_COVERAGE_BY_SLUG = new Map(SOURCE_COVERAGE.map((source) => [source.slug, source]));
