export type SourceCoverage = {
  slug: string;
  label: string;
  connection: "live_api" | "oauth_api" | "catalog_api" | "paid_api" | "export" | "public";
  status: "available" | "configuration_required" | "export_required" | "paid_key_required" | "limited";
  summary: string;
  metrics: string[];
  limitation?: string;
};

export const SOURCE_COVERAGE: SourceCoverage[] = [
  {
    slug: "youtube",
    label: "YouTube / YouTube Music",
    connection: "oauth_api",
    status: "configuration_required",
    summary: "Owned-channel totals and YouTube Analytics through Google OAuth.",
    metrics: ["subscribers", "channel views", "videos", "views", "watch minutes", "average view duration", "likes", "comments", "shares", "subscriber gains/losses"],
    limitation: "The YouTube Data API v3 and YouTube Analytics API must be enabled, the required scopes authorized, and a successful request recorded before ArtistOS can call the source provider verified.",
  },
  {
    slug: "soundcharts",
    label: "Soundcharts pilot",
    connection: "live_api",
    status: "configuration_required",
    summary: "Cross-platform audience, Spotify monthly listeners, playlist entries, charts, radio, and social observations through a licensed API.",
    metrics: ["monthly listeners", "followers", "playlist entries", "charts", "radio", "social audience"],
    limitation: "Endpoint access and allowed storage depend on the active Soundcharts account, contract, and credentials.",
  },
  {
    slug: "kit",
    label: "Kit email audience",
    connection: "live_api",
    status: "configuration_required",
    summary: "Aggregate subscriber and broadcast performance from the owned Kit account.",
    metrics: ["active subscribers", "broadcast recipients", "opens", "clicks", "unsubscribes", "open rate", "click rate"],
    limitation: "Requires a Kit v4 API key. ArtistOS stores aggregate metrics only in the first slice, not raw subscriber records.",
  },
  {
    slug: "spotify",
    label: "Spotify",
    connection: "catalog_api",
    status: "limited",
    summary: "Catalog identity, releases, tracks and URLs through the Web API; private artist analytics through exports or a licensed provider.",
    metrics: ["catalog metadata", "release identity", "track identity", "Spotify for Artists export"],
    limitation: "Spotify's February 2026 Development Mode restrictions removed fields such as artist followers and popularity and narrowed several endpoints. Extended Quota Mode apps are not covered by those Development Mode restrictions. Streams and monthly listeners still are not public artist-analytics fields.",
  },
  {
    slug: "apple-music",
    label: "Apple Music",
    connection: "catalog_api",
    status: "configuration_required",
    summary: "Public catalog, charts, playlists, artist and release identity through Apple Music API; private artist performance through Apple Music for Artists exports.",
    metrics: ["catalog metadata", "charts", "playlists", "plays export", "listeners export", "Shazam counts export"],
    limitation: "The catalog API requires an Apple developer token. ArtistOS must not present catalog access as authorization to private Apple Music for Artists analytics.",
  },
  {
    slug: "instagram",
    label: "Instagram / Facebook",
    connection: "oauth_api",
    status: "configuration_required",
    summary: "Professional-account reach, engagement, audience and media performance through Meta authorization.",
    metrics: ["followers", "reach", "profile views", "likes", "comments", "shares", "saves", "reel and video performance"],
    limitation: "Requires an eligible professional Instagram account, the correct Meta app permissions and a successful insights request. Some audience metrics are unavailable for smaller accounts or outside the retained reporting window.",
  },
  {
    slug: "tiktok",
    label: "TikTok",
    connection: "oauth_api",
    status: "configuration_required",
    summary: "Authorized account totals and owned-video engagement through approved TikTok scopes.",
    metrics: ["followers", "following", "profile likes", "video count", "video views", "likes", "comments", "shares"],
    limitation: "Requires TikTok developer approval, Login Kit or equivalent authorization, and scopes such as user.info.stats plus eligible video access. Public profile identity alone is not a live analytics connection.",
  },
  {
    slug: "soundcloud",
    label: "SoundCloud",
    connection: "oauth_api",
    status: "configuration_required",
    summary: "Authorized profile, track, play, like, repost and comment data where SoundCloud grants API access.",
    metrics: ["followers", "plays", "likes", "reposts", "comments"],
    limitation: "Current integrations should use SoundCloud OAuth 2.1 with PKCE, short-lived access tokens and rotated refresh tokens. API approval and endpoint access are still required.",
  },
  {
    slug: "audius",
    label: "Audius",
    connection: "public",
    status: "available",
    summary: "Public artist, track, playlist and play-count signals through the Audius API and SDK.",
    metrics: ["artist identity", "track identity", "play count", "favorites", "reposts", "playlist membership"],
    limitation: "Audius public activity is a platform-specific signal. It does not represent all DSP streams, royalties or private artist-dashboard analytics.",
  },
  {
    slug: "lastfm",
    label: "Last.fm",
    connection: "live_api",
    status: "configuration_required",
    summary: "Free-key public popularity, track playcount, similar-artist, and chart signals.",
    metrics: ["listeners", "playcount", "track playcount", "similar artists", "charts"],
    limitation: "Requires a free Last.fm API key and is a public discovery signal, not a DSP royalty or artist-dashboard source.",
  },
  {
    slug: "listenbrainz",
    label: "ListenBrainz",
    connection: "public",
    status: "available",
    summary: "Open listens-derived popularity, statistics, recommendations, and similar-artist signals.",
    metrics: ["popularity", "listen counts", "similar artists", "recommendations"],
    limitation: "Coverage reflects listens submitted to ListenBrainz and should be treated as a directional open-data signal.",
  },
  {
    slug: "musicbrainz",
    label: "MusicBrainz",
    connection: "public",
    status: "limited",
    summary: "Canonical artist, release, recording, ISRC, barcode, label, and relationship metadata.",
    metrics: ["artist identity", "release identity", "recordings", "ISRC", "barcode", "relationships"],
    limitation: "The public web service is free for non-commercial use, rate limited, and requires terms review for a commercial ArtistOS product.",
  },
  {
    slug: "ticketmaster",
    label: "Ticketmaster Discovery",
    connection: "live_api",
    status: "configuration_required",
    summary: "Event, venue, attraction, geography, and ticket-link intelligence through a developer key.",
    metrics: ["events", "venues", "markets", "dates", "ticket links"],
    limitation: "Coverage varies by market and requires a Ticketmaster developer key.",
  },
  {
    slug: "distrokid",
    label: "DistroKid / distributor reports",
    connection: "export",
    status: "export_required",
    summary: "Royalty and store-level performance from distributor CSV exports.",
    metrics: ["streams", "earnings", "store", "territory", "release", "reporting period"],
    limitation: "DistroKid does not provide a general public analytics API for this use case.",
  },
  {
    slug: "chartmetric",
    label: "Chartmetric",
    connection: "paid_api",
    status: "paid_key_required",
    summary: "Licensed cross-platform artist, playlist, chart, audience, and competitor intelligence.",
    metrics: ["playlist movement", "charts", "audience", "social growth", "competitor benchmarks"],
    limitation: "Use only under an active licensed API agreement that permits the requested endpoints, storage and display.",
  },
  {
    slug: "viberate",
    label: "Viberate",
    connection: "paid_api",
    status: "paid_key_required",
    summary: "Licensed artist analytics, audience, playlist, festival, and industry benchmarks.",
    metrics: ["artist performance", "audience", "playlists", "industry benchmarks"],
    limitation: "Use only under an active licensed API agreement. Do not imply access from a normal product subscription or public profile page.",
  },
  {
    slug: "bandcamp",
    label: "Bandcamp",
    connection: "export",
    status: "export_required",
    summary: "Direct-to-fan sales, supporters, and geography through exports and public release metadata.",
    metrics: ["sales", "supporters", "revenue", "territory"],
  },
];

export const SOURCE_COVERAGE_BY_SLUG = new Map(SOURCE_COVERAGE.map((source) => [source.slug, source]));
